/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-fixed": "#410003",
        "surface": "#f8f9fa",
        "background": "#f8f9fa",
        "on-primary-container": "#88e274",
        "secondary": "#735c00",
        "on-secondary-container": "#6f5900",
        "on-error": "#ffffff",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#bfcab7",
        "surface-dim": "#d9dadb",
        "tertiary": "#86000d",
        "on-surface-variant": "#404a3b",
        "on-secondary-fixed": "#231b00",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb3ac",
        "on-background": "#191c1d",
        "secondary-fixed-dim": "#eec209",
        "secondary-fixed": "#ffe084",
        "tertiary-container": "#af0f1a",
        "inverse-surface": "#2e3132",
        "primary": "#004b00",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "on-error-container": "#93000a",
        "surface-container": "#edeeef",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed-variant": "#574500",
        "on-primary-fixed-variant": "#005300",
        "surface-tint": "#106e09",
        "on-tertiary-fixed-variant": "#930010",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#81db6e",
        "primary-container": "#006600",
        "primary-fixed": "#9cf987",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#ffdad6",
        "inverse-primary": "#81db6e",
        "secondary-container": "#fed023",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-container": "#ffbdb7",
        "outline": "#707a6a",
        "on-primary-fixed": "#002200"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "stack-lg": "24px",
        "gutter": "16px",
        "container-padding": "20px",
        "stack-md": "12px",
        "stack-lg": "24px"
      },
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
